spring.application.name=managemnt

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ems_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Kisal@#123

# Hibernate/JPA Configuration
# 'update' automatically creates/updates database tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kisalranaabey03@gmail.com
spring.mail.password=iumikgmoahnvvbwj

# SMTP Security Settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

